# Auto-extracted from pokeemerald-master + trainer data
# Used by BattleMessageMatcher to validate VAR slot values
import re

# ---------- exact game display strings ----------

STAT_NAMES: list[str] = [
    "HP", "ATTACK", "DEFENSE", "SPEED", "SP. ATK", "SP. DEF",
    "accuracy", "evasiveness",
]

TYPE_NAMES: list[str] = [
    "NORMAL", "FIGHT", "FLYING", "POISON", "GROUND", "ROCK",
    "BUG", "GHOST", "STEEL", "???", "FIRE", "WATER", "GRASS",
    "ELECTR", "PSYCHC", "ICE", "DRAGON", "DARK",
]

# ---------- frozensets for O(1) lookup ----------

POKEMON_NAMES: frozenset[str] = frozenset({
    "ABRA",
    "ABSOL",
    "AERODACTYL",
    "AGGRON",
    "AIPOM",
    "ALAKAZAM",
    "ALTARIA",
    "AMPHAROS",
    "ANORITH",
    "ARBOK",
    "ARCANINE",
    "ARIADOS",
    "ARMALDO",
    "ARON",
    "ARTICUNO",
    "AZUMARILL",
    "AZURILL",
    "BAGON",
    "BALTOY",
    "BANETTE",
    "BARBOACH",
    "BAYLEEF",
    "BEAUTIFLY",
    "BEEDRILL",
    "BELDUM",
    "BELLOSSOM",
    "BELLSPROUT",
    "BLASTOISE",
    "BLAZIKEN",
    "BLISSEY",
    "BRELOOM",
    "BULBASAUR",
    "BUTTERFREE",
    "CACNEA",
    "CACTURNE",
    "CAMERUPT",
    "CARVANHA",
    "CASCOON",
    "CASTFORM",
    "CATERPIE",
    "CELEBI",
    "CHANSEY",
    "CHARIZARD",
    "CHARMANDER",
    "CHARMELEON",
    "CHIKORITA",
    "CHIMECHO",
    "CHINCHOU",
    "CLAMPERL",
    "CLAYDOL",
    "CLEFABLE",
    "CLEFAIRY",
    "CLEFFA",
    "CLOYSTER",
    "COMBUSKEN",
    "CORPHISH",
    "CORSOLA",
    "CRADILY",
    "CRAWDAUNT",
    "CROBAT",
    "CROCONAW",
    "CUBONE",
    "CYNDAQUIL",
    "DELCATTY",
    "DELIBIRD",
    "DEOXYS",
    "DEWGONG",
    "DIGLETT",
    "DITTO",
    "DODRIO",
    "DODUO",
    "DONPHAN",
    "DRAGONAIR",
    "DRAGONITE",
    "DRATINI",
    "DROWZEE",
    "DUGTRIO",
    "DUNSPARCE",
    "DUSCLOPS",
    "DUSKULL",
    "DUSTOX",
    "EEVEE",
    "EKANS",
    "ELECTABUZZ",
    "ELECTRIKE",
    "ELECTRODE",
    "ELEKID",
    "ENTEI",
    "ESPEON",
    "EXEGGCUTE",
    "EXEGGUTOR",
    "EXPLOUD",
    "FARFETCH'D",
    "FEAROW",
    "FEEBAS",
    "FERALIGATR",
    "FLAAFFY",
    "FLAREON",
    "FLYGON",
    "FORRETRESS",
    "FURRET",
    "GARDEVOIR",
    "GASTLY",
    "GENGAR",
    "GEODUDE",
    "GIRAFARIG",
    "GLALIE",
    "GLIGAR",
    "GLOOM",
    "GOLBAT",
    "GOLDEEN",
    "GOLDUCK",
    "GOLEM",
    "GOREBYSS",
    "GRANBULL",
    "GRAVELER",
    "GRIMER",
    "GROUDON",
    "GROVYLE",
    "GROWLITHE",
    "GRUMPIG",
    "GULPIN",
    "GYARADOS",
    "HARIYAMA",
    "HAUNTER",
    "HERACROSS",
    "HITMONCHAN",
    "HITMONLEE",
    "HITMONTOP",
    "HO-OH",
    "HOOTHOOT",
    "HOPPIP",
    "HORSEA",
    "HOUNDOOM",
    "HOUNDOUR",
    "HUNTAIL",
    "HYPNO",
    "IGGLYBUFF",
    "ILLUMISE",
    "IVYSAUR",
    "JIGGLYPUFF",
    "JIRACHI",
    "JOLTEON",
    "JUMPLUFF",
    "JYNX",
    "KABUTO",
    "KABUTOPS",
    "KADABRA",
    "KAKUNA",
    "KANGASKHAN",
    "KECLEON",
    "KINGDRA",
    "KINGLER",
    "KIRLIA",
    "KOFFING",
    "KRABBY",
    "KYOGRE",
    "LAIRON",
    "LANTURN",
    "LAPRAS",
    "LARVITAR",
    "LATIAS",
    "LATIOS",
    "LEDIAN",
    "LEDYBA",
    "LICKITUNG",
    "LILEEP",
    "LINOONE",
    "LOMBRE",
    "LOTAD",
    "LOUDRED",
    "LUDICOLO",
    "LUGIA",
    "LUNATONE",
    "LUVDISC",
    "MACHAMP",
    "MACHOKE",
    "MACHOP",
    "MAGBY",
    "MAGCARGO",
    "MAGIKARP",
    "MAGMAR",
    "MAGNEMITE",
    "MAGNETON",
    "MAKUHITA",
    "MANECTRIC",
    "MANKEY",
    "MANTINE",
    "MAREEP",
    "MARILL",
    "MAROWAK",
    "MARSHTOMP",
    "MASQUERAIN",
    "MAWILE",
    "MEDICHAM",
    "MEDITITE",
    "MEGANIUM",
    "MEOWTH",
    "METAGROSS",
    "METANG",
    "METAPOD",
    "MEW",
    "MEWTWO",
    "MIGHTYENA",
    "MILOTIC",
    "MILTANK",
    "MINUN",
    "MISDREAVUS",
    "MOLTRES",
    "MR. MIME",
    "MUDKIP",
    "MUK",
    "MURKROW",
    "NATU",
    "NIDOKING",
    "NIDOQUEEN",
    "NIDORAN♀",
    "NIDORAN♂",
    "NIDORINA",
    "NIDORINO",
    "NINCADA",
    "NINETALES",
    "NINJASK",
    "NOCTOWL",
    "NOSEPASS",
    "NUMEL",
    "NUZLEAF",
    "OCTILLERY",
    "ODDISH",
    "OMANYTE",
    "OMASTAR",
    "ONIX",
    "PARAS",
    "PARASECT",
    "PELIPPER",
    "PERSIAN",
    "PHANPY",
    "PICHU",
    "PIDGEOT",
    "PIDGEOTTO",
    "PIDGEY",
    "PIKACHU",
    "PILOSWINE",
    "PINECO",
    "PINSIR",
    "PLUSLE",
    "POLITOED",
    "POLIWAG",
    "POLIWHIRL",
    "POLIWRATH",
    "PONYTA",
    "POOCHYENA",
    "PORYGON",
    "PORYGON2",
    "PRIMEAPE",
    "PSYDUCK",
    "PUPITAR",
    "QUAGSIRE",
    "QUILAVA",
    "QWILFISH",
    "RAICHU",
    "RAIKOU",
    "RALTS",
    "RAPIDASH",
    "RATICATE",
    "RATTATA",
    "RAYQUAZA",
    "REGICE",
    "REGIROCK",
    "REGISTEEL",
    "RELICANTH",
    "REMORAID",
    "RHYDON",
    "RHYHORN",
    "ROSELIA",
    "SABLEYE",
    "SALAMENCE",
    "SANDSHREW",
    "SANDSLASH",
    "SCEPTILE",
    "SCIZOR",
    "SCYTHER",
    "SEADRA",
    "SEAKING",
    "SEALEO",
    "SEEDOT",
    "SEEL",
    "SENTRET",
    "SEVIPER",
    "SHARPEDO",
    "SHEDINJA",
    "SHELGON",
    "SHELLDER",
    "SHIFTRY",
    "SHROOMISH",
    "SHUCKLE",
    "SHUPPET",
    "SILCOON",
    "SKARMORY",
    "SKIPLOOM",
    "SKITTY",
    "SLAKING",
    "SLAKOTH",
    "SLOWBRO",
    "SLOWKING",
    "SLOWPOKE",
    "SLUGMA",
    "SMEARGLE",
    "SMOOCHUM",
    "SNEASEL",
    "SNORLAX",
    "SNORUNT",
    "SNUBBULL",
    "SOLROCK",
    "SPEAROW",
    "SPHEAL",
    "SPINARAK",
    "SPINDA",
    "SPOINK",
    "SQUIRTLE",
    "STANTLER",
    "STARMIE",
    "STARYU",
    "STEELIX",
    "SUDOWOODO",
    "SUICUNE",
    "SUNFLORA",
    "SUNKERN",
    "SURSKIT",
    "SWABLU",
    "SWALOT",
    "SWAMPERT",
    "SWELLOW",
    "SWINUB",
    "TAILLOW",
    "TANGELA",
    "TAUROS",
    "TEDDIURSA",
    "TENTACOOL",
    "TENTACRUEL",
    "TOGEPI",
    "TOGETIC",
    "TORCHIC",
    "TORKOAL",
    "TOTODILE",
    "TRAPINCH",
    "TREECKO",
    "TROPIUS",
    "TYPHLOSION",
    "TYRANITAR",
    "TYROGUE",
    "UMBREON",
    "UNOWN",
    "URSARING",
    "VAPOREON",
    "VENOMOTH",
    "VENONAT",
    "VENUSAUR",
    "VIBRAVA",
    "VICTREEBEL",
    "VIGOROTH",
    "VILEPLUME",
    "VOLBEAT",
    "VOLTORB",
    "VULPIX",
    "WAILMER",
    "WAILORD",
    "WALREIN",
    "WARTORTLE",
    "WEEDLE",
    "WEEPINBELL",
    "WEEZING",
    "WHISCASH",
    "WHISMUR",
    "WIGGLYTUFF",
    "WINGULL",
    "WOBBUFFET",
    "WOOPER",
    "WURMPLE",
    "WYNAUT",
    "XATU",
    "YANMA",
    "ZANGOOSE",
    "ZAPDOS",
    "ZIGZAGOON",
    "ZUBAT",
})

# The base frozenset above is vanilla-Emerald-only (Gen 1-3). Run & Bun adds the
# full Gen 4-8 roster, so an OCR'd name like "Budew" hits the unconstrained
# validation path (constraints=None) and is rejected, crashing the matcher.
# Mirror MOVE_NAMES: union in the emulator display name of EVERY Species enum
# member. Forms render under their base name (handled by emulator_species_name),
# and extra form names only loosen unconstrained validation — they never reject a
# real OCR name, since every base name is present.
def _all_species_display_names() -> frozenset[str]:
    from liveplay.data.species import Species
    from liveplay.data.name_aliases import emulator_species_name
    return frozenset(emulator_species_name(s).upper() for s in Species)


POKEMON_NAMES = POKEMON_NAMES | _all_species_display_names()

MOVE_NAMES: frozenset[str] = frozenset({
    "ABSORB",
    "ACID",
    "ACID ARMOR",
    "AERIAL ACE",
    "AEROBLAST",
    "AGILITY",
    "AIR CUTTER",
    "AMNESIA",
    "ANCIENTPOWER",
    "ARM THRUST",
    "AROMATHERAPY",
    "ASSIST",
    "ASTONISH",
    "ATTRACT",
    "AURORA BEAM",
    "BARRAGE",
    "BARRIER",
    "BATON PASS",
    "BEAT UP",
    "BELLY DRUM",
    "BIND",
    "BITE",
    "BLAST BURN",
    "BLAZE KICK",
    "BLIZZARD",
    "BLOCK",
    "BODY SLAM",
    "BONE CLUB",
    "BONE RUSH",
    "BONEMERANG",
    "BOUNCE",
    "BRICK BREAK",
    "BUBBLE",
    "BUBBLEBEAM",
    "BULK UP",
    "BULLET SEED",
    "CALM MIND",
    "CAMOUFLAGE",
    "CHARGE",
    "CHARM",
    "CLAMP",
    "COMET PUNCH",
    "CONFUSE RAY",
    "CONFUSION",
    "CONSTRICT",
    "CONVERSION",
    "CONVERSION 2",
    "COSMIC POWER",
    "COTTON SPORE",
    "COUNTER",
    "COVET",
    "CRABHAMMER",
    "CROSS CHOP",
    "CRUNCH",
    "CRUSH CLAW",
    "CURSE",
    "CUT",
    "DEFENSE CURL",
    "DESTINY BOND",
    "DETECT",
    "DIG",
    "DISABLE",
    "DIVE",
    "DIZZY PUNCH",
    "DOOM DESIRE",
    "DOUBLE KICK",
    "DOUBLE TEAM",
    "DOUBLE-EDGE",
    "DOUBLESLAP",
    "DRAGON CLAW",
    "DRAGON DANCE",
    "DRAGON RAGE",
    "DRAGONBREATH",
    "DREAM EATER",
    "DRILL PECK",
    "DYNAMICPUNCH",
    "EARTHQUAKE",
    "EGG BOMB",
    "EMBER",
    "ENCORE",
    "ENDEAVOR",
    "ENDURE",
    "ERUPTION",
    "EXPLOSION",
    "EXTRASENSORY",
    "EXTREMESPEED",
    "FACADE",
    "FAINT ATTACK",
    "FAKE OUT",
    "FAKE TEARS",
    "FALSE SWIPE",
    "FEATHERDANCE",
    "FIRE BLAST",
    "FIRE PUNCH",
    "FIRE SPIN",
    "FISSURE",
    "FLAIL",
    "FLAME WHEEL",
    "FLAMETHROWER",
    "FLASH",
    "FLATTER",
    "FLY",
    "FOCUS ENERGY",
    "FOCUS PUNCH",
    "FOLLOW ME",
    "FORESIGHT",
    "FRENZY PLANT",
    "FRUSTRATION",
    "FURY ATTACK",
    "FURY CUTTER",
    "FURY SWIPES",
    "FUTURE SIGHT",
    "GIGA DRAIN",
    "GLARE",
    "GRASSWHISTLE",
    "GROWL",
    "GROWTH",
    "GRUDGE",
    "GUILLOTINE",
    "GUST",
    "HAIL",
    "HARDEN",
    "HAZE",
    "HEADBUTT",
    "HEAL BELL",
    "HEAT WAVE",
    "HELPING HAND",
    "HI JUMP KICK",
    "HIDDEN POWER",
    "HORN ATTACK",
    "HORN DRILL",
    "HOWL",
    "HYDRO CANNON",
    "HYDRO PUMP",
    "HYPER BEAM",
    "HYPER FANG",
    "HYPER VOICE",
    "HYPNOSIS",
    "ICE BALL",
    "ICE BEAM",
    "ICE PUNCH",
    "ICICLE SPEAR",
    "ICY WIND",
    "IMPRISON",
    "INGRAIN",
    "IRON DEFENSE",
    "IRON TAIL",
    "JUMP KICK",
    "KARATE CHOP",
    "KINESIS",
    "KNOCK OFF",
    "LEAF BLADE",
    "LEECH LIFE",
    "LEECH SEED",
    "LEER",
    "LICK",
    "LIGHT SCREEN",
    "LOCK-ON",
    "LOVELY KISS",
    "LOW KICK",
    "LUSTER PURGE",
    "MACH PUNCH",
    "MAGIC COAT",
    "MAGICAL LEAF",
    "MAGNITUDE",
    "MEAN LOOK",
    "MEDITATE",
    "MEGA DRAIN",
    "MEGA KICK",
    "MEGA PUNCH",
    "MEGAHORN",
    "MEMENTO",
    "METAL CLAW",
    "METAL SOUND",
    "METEOR MASH",
    "METRONOME",
    "MILK DRINK",
    "MIMIC",
    "MIND READER",
    "MINIMIZE",
    "MIRROR COAT",
    "MIRROR MOVE",
    "MIST",
    "MIST BALL",
    "MOONLIGHT",
    "MORNING SUN",
    "MUD SHOT",
    "MUD SPORT",
    "MUD-SLAP",
    "MUDDY WATER",
    "NATURE POWER",
    "NEEDLE ARM",
    "NIGHT SHADE",
    "NIGHTMARE",
    "OCTAZOOKA",
    "ODOR SLEUTH",
    "OUTRAGE",
    "OVERHEAT",
    "PAIN SPLIT",
    "PAY DAY",
    "PECK",
    "PERISH SONG",
    "PETAL DANCE",
    "PIN MISSILE",
    "POISON FANG",
    "POISON GAS",
    "POISON STING",
    "POISON TAIL",
    "POISONPOWDER",
    "POUND",
    "POWDER SNOW",
    "PRESENT",
    "PROTECT",
    "PSYBEAM",
    "PSYCH UP",
    "PSYCHIC",
    "PSYCHO BOOST",
    "PSYWAVE",
    "PURSUIT",
    "QUICK ATTACK",
    "RAGE",
    "RAIN DANCE",
    "RAPID SPIN",
    "RAZOR LEAF",
    "RAZOR WIND",
    "RECOVER",
    "RECYCLE",
    "REFLECT",
    "REFRESH",
    "REST",
    "RETURN",
    "REVENGE",
    "REVERSAL",
    "ROAR",
    "ROCK BLAST",
    "ROCK SLIDE",
    "ROCK SMASH",
    "ROCK THROW",
    "ROCK TOMB",
    "ROLE PLAY",
    "ROLLING KICK",
    "ROLLOUT",
    "SACRED FIRE",
    "SAFEGUARD",
    "SAND TOMB",
    "SAND-ATTACK",
    "SANDSTORM",
    "SCARY FACE",
    "SCRATCH",
    "SCREECH",
    "SECRET POWER",
    "SEISMIC TOSS",
    "SELFDESTRUCT",
    "SHADOW BALL",
    "SHADOW PUNCH",
    "SHARPEN",
    "SHEER COLD",
    "SHOCK WAVE",
    "SIGNAL BEAM",
    "SILVER WIND",
    "SING",
    "SKETCH",
    "SKILL SWAP",
    "SKULL BASH",
    "SKY ATTACK",
    "SKY UPPERCUT",
    "SLACK OFF",
    "SLAM",
    "SLASH",
    "SLEEP POWDER",
    "SLEEP TALK",
    "SLUDGE",
    "SLUDGE BOMB",
    "SMELLINGSALT",
    "SMOG",
    "SMOKESCREEN",
    "SNATCH",
    "SNORE",
    "SOFTBOILED",
    "SOLARBEAM",
    "SONICBOOM",
    "SPARK",
    "SPIDER WEB",
    "SPIKE CANNON",
    "SPIKES",
    "SPIT UP",
    "SPITE",
    "SPLASH",
    "SPORE",
    "STEEL WING",
    "STOCKPILE",
    "STOMP",
    "STRENGTH",
    "STRING SHOT",
    "STRUGGLE",
    "STUN SPORE",
    "SUBMISSION",
    "SUBSTITUTE",
    "SUNNY DAY",
    "SUPER FANG",
    "SUPERPOWER",
    "SUPERSONIC",
    "SURF",
    "SWAGGER",
    "SWALLOW",
    "SWEET KISS",
    "SWEET SCENT",
    "SWIFT",
    "SWORDS DANCE",
    "SYNTHESIS",
    "TACKLE",
    "TAIL GLOW",
    "TAIL WHIP",
    "TAKE DOWN",
    "TAUNT",
    "TEETER DANCE",
    "TELEPORT",
    "THIEF",
    "THRASH",
    "THUNDER",
    "THUNDER WAVE",
    "THUNDERBOLT",
    "THUNDERPUNCH",
    "THUNDERSHOCK",
    "TICKLE",
    "TORMENT",
    "TOXIC",
    "TRANSFORM",
    "TRI ATTACK",
    "TRICK",
    "TRIPLE KICK",
    "TWINEEDLE",
    "TWISTER",
    "UPROAR",
    "VICEGRIP",
    "VINE WHIP",
    "VITAL THROW",
    "VOLT TACKLE",
    "WATER GUN",
    "WATER PULSE",
    "WATER SPORT",
    "WATER SPOUT",
    "WATERFALL",
    "WEATHER BALL",
    "WHIRLPOOL",
    "WHIRLWIND",
    "WILL-O-WISP",
    "WING ATTACK",
    "WISH",
    "WITHDRAW",
    "WRAP",
    "YAWN",
    "ZAP CANNON",
})

# A move can appear in a "used <move>!" message via direct use OR a Metronome call,
# so the matcher must be able to parse the display name of EVERY implemented move.
# Per project rule "implemented = in the Move enum", union in the display name of
# every Move enum member (this supersedes the older Metronome-callable-only union,
# which wrongly excluded in-enum-but-METRONOME_EXCLUDED moves like Heal Pulse, Dig,
# Counter, etc. — Issue 22). Moves absent from the enum (unmodeled romhack additions)
# remain unparseable — accepted per scope.
def _all_move_display_names() -> frozenset[str]:
    from liveplay.data.moves import Move
    return frozenset(m.name.replace("_", " ") for m in Move if m.name != "NONE")


MOVE_NAMES = MOVE_NAMES | _all_move_display_names()

ITEM_NAMES: frozenset[str] = frozenset({
    "ACRO BIKE",
    "AGUAV BERRY",
    "AMULET COIN",
    "ANTIDOTE",
    "APICOT BERRY",
    "ASPEAR BERRY",
    "AURORATICKET",
    "AWAKENING",
    "BASEMENT KEY",
    "BEAD MAIL",
    "BELUE BERRY",
    "BERRY JUICE",
    "BERRY POUCH",
    "BICYCLE",
    "BIG MUSHROOM",
    "BIG PEARL",
    "BIKE VOUCHER",
    "BLACK BELT",
    "BLACK FLUTE",
    "BLACKGLASSES",
    "BLUE FLUTE",
    "BLUE ORB",
    "BLUE SCARF",
    "BLUE SHARD",
    "BLUK BERRY",
    "BRIGHTPOWDER",
    "BURN HEAL",
    "CALCIUM",
    "CARBOS",
    "CARD KEY",
    "CHARCOAL",
    "CHERI BERRY",
    "CHESTO BERRY",
    "CHOICE BAND",
    "CLAW FOSSIL",
    "CLEANSE TAG",
    "COIN CASE",
    "CONTEST PASS",
    "CORNN BERRY",
    "DEEPSEASCALE",
    "DEEPSEATOOTH",
    "DEVON GOODS",
    "DEVON SCOPE",
    "DIRE HIT",
    "DIVE BALL",
    "DOME FOSSIL",
    "DRAGON FANG",
    "DRAGON SCALE",
    "DREAM MAIL",
    "DURIN BERRY",
    "ELIXIR",
    "ENERGY ROOT",
    "ENERGYPOWDER",
    "ENIGMA BERRY",
    "EON TICKET",
    "ESCAPE ROPE",
    "ETHER",
    "EVERSTONE",
    "EXP. SHARE",
    "FAB MAIL",
    "FAME CHECKER",
    "FIGY BERRY",
    "FIRE STONE",
    "FLUFFY TAIL",
    "FOCUS BAND",
    "FRESH WATER",
    "FULL HEAL",
    "FULL RESTORE",
    "GANLON BERRY",
    "GLITTER MAIL",
    "GO-GOGGLES",
    "GOLD TEETH",
    "GOOD ROD",
    "GREAT BALL",
    "GREEN SCARF",
    "GREEN SHARD",
    "GREPA BERRY",
    "GUARD SPEC.",
    "HARBOR MAIL",
    "HARD STONE",
    "HEAL POWDER",
    "HEART SCALE",
    "HELIX FOSSIL",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "HM06",
    "HM07",
    "HM08",
    "HONDEW BERRY",
    "HP UP",
    "HYPER POTION",
    "IAPAPA BERRY",
    "ICE HEAL",
    "IRON",
    "ITEMFINDER",
    "KELPSY BERRY",
    "KING'S ROCK",
    "LANSAT BERRY",
    "LAVA COOKIE",
    "LAX INCENSE",
    "LEAF STONE",
    "LEFTOVERS",
    "LEMONADE",
    "LEPPA BERRY",
    "LETTER",
    "LIECHI BERRY",
    "LIFT KEY",
    "LIGHT BALL",
    "LUCKY EGG",
    "LUCKY PUNCH",
    "LUM BERRY",
    "LUXURY BALL",
    "MACH BIKE",
    "MACHO BRACE",
    "MAGMA EMBLEM",
    "MAGNET",
    "MAGO BERRY",
    "MAGOST BERRY",
    "MASTER BALL",
    "MAX ELIXIR",
    "MAX ETHER",
    "MAX POTION",
    "MAX REPEL",
    "MAX REVIVE",
    "MECH MAIL",
    "MENTAL HERB",
    "METAL COAT",
    "METAL POWDER",
    "METEORITE",
    "MIRACLE SEED",
    "MOOMOO MILK",
    "MOON STONE",
    "MYSTIC WATER",
    "MYSTICTICKET",
    "NANAB BERRY",
    "NEST BALL",
    "NET BALL",
    "NEVERMELTICE",
    "NOMEL BERRY",
    "NUGGET",
    "OAK'S PARCEL",
    "OLD AMBER",
    "OLD ROD",
    "OLD SEA MAP",
    "ORAN BERRY",
    "ORANGE MAIL",
    "PAMTRE BERRY",
    "PARLYZ HEAL",
    "PEARL",
    "PECHA BERRY",
    "PERSIM BERRY",
    "PETAYA BERRY",
    "PINAP BERRY",
    "PINK SCARF",
    "POISON BARB",
    "POKé BALL",
    "POKé DOLL",
    "POKé FLUTE",
    "POMEG BERRY",
    "POTION",
    "POWDER JAR",
    "PP MAX",
    "PP UP",
    "PREMIER BALL",
    "PROTEIN",
    "QUALOT BERRY",
    "QUICK CLAW",
    "RABUTA BERRY",
    "RAINBOW PASS",
    "RARE CANDY",
    "RAWST BERRY",
    "RAZZ BERRY",
    "RED FLUTE",
    "RED ORB",
    "RED SCARF",
    "RED SHARD",
    "REPEAT BALL",
    "REPEL",
    "RETRO MAIL",
    "REVIVAL HERB",
    "REVIVE",
    "RM. 1 KEY",
    "RM. 2 KEY",
    "RM. 4 KEY",
    "RM. 6 KEY",
    "ROOT FOSSIL",
    "RUBY",
    "S.S. TICKET",
    "SACRED ASH",
    "SAFARI BALL",
    "SALAC BERRY",
    "SAPPHIRE",
    "SCANNER",
    "SCOPE LENS",
    "SEA INCENSE",
    "SECRET KEY",
    "SHADOW MAIL",
    "SHARP BEAK",
    "SHELL BELL",
    "SHOAL SALT",
    "SHOAL SHELL",
    "SILK SCARF",
    "SILPH SCOPE",
    "SILVERPOWDER",
    "SITRUS BERRY",
    "SMOKE BALL",
    "SODA POP",
    "SOFT SAND",
    "SOOT SACK",
    "SOOTHE BELL",
    "SOUL DEW",
    "SPELL TAG",
    "SPELON BERRY",
    "STAR PIECE",
    "STARDUST",
    "STARF BERRY",
    "STICK",
    "STORAGE KEY",
    "SUN STONE",
    "SUPER POTION",
    "SUPER REPEL",
    "SUPER ROD",
    "TAMATO BERRY",
    "TEA",
    "TEACHY TV",
    "THICK CLUB",
    "THUNDERSTONE",
    "TIMER BALL",
    "TINYMUSHROOM",
    "TM CASE",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "TOWN MAP",
    "TRI-PASS",
    "TROPIC MAIL",
    "TWISTEDSPOON",
    "ULTRA BALL",
    "UP-GRADE",
    "VS SEEKER",
    "WAILMER PAIL",
    "WATER STONE",
    "WATMEL BERRY",
    "WAVE MAIL",
    "WEPEAR BERRY",
    "WHITE FLUTE",
    "WHITE HERB",
    "WIKI BERRY",
    "WOOD MAIL",
    "X ACCURACY",
    "X ATTACK",
    "X DEFEND",
    "X SPECIAL",
    "X SPEED",
    "YELLOW FLUTE",
    "YELLOW SCARF",
    "YELLOW SHARD",
    "ZINC",
})

ABILITY_NAMES: frozenset[str] = frozenset({
    "AIR LOCK",
    "ARENA TRAP",
    "BATTLE ARMOR",
    "BLAZE",
    "CACOPHONY",
    "CHLOROPHYLL",
    "CLEAR BODY",
    "CLOUD NINE",
    "COLOR CHANGE",
    "COMPOUNDEYES",
    "CUTE CHARM",
    "DAMP",
    "DRIZZLE",
    "DROUGHT",
    "EARLY BIRD",
    "EFFECT SPORE",
    "FLAME BODY",
    "FLASH FIRE",
    "FORECAST",
    "GUTS",
    "HUGE POWER",
    "HUSTLE",
    "HYPER CUTTER",
    "ILLUMINATE",
    "IMMUNITY",
    "INNER FOCUS",
    "INSOMNIA",
    "INTIMIDATE",
    "KEEN EYE",
    "LEVITATE",
    "LIGHTNINGROD",
    "LIMBER",
    "LIQUID OOZE",
    "MAGMA ARMOR",
    "MAGNET PULL",
    "MARVEL SCALE",
    "MINUS",
    "NATURAL CURE",
    "OBLIVIOUS",
    "OVERGROW",
    "OWN TEMPO",
    "PICKUP",
    "PLUS",
    "POISON POINT",
    "PRESSURE",
    "PURE POWER",
    "RAIN DISH",
    "ROCK HEAD",
    "ROUGH SKIN",
    "RUN AWAY",
    "SAND STREAM",
    "SAND VEIL",
    "SERENE GRACE",
    "SHADOW TAG",
    "SHED SKIN",
    "SHELL ARMOR",
    "SHIELD DUST",
    "SOUNDPROOF",
    "SPEED BOOST",
    "STATIC",
    "STENCH",
    "STICKY HOLD",
    "STURDY",
    "SUCTION CUPS",
    "SWARM",
    "SWIFT SWIM",
    "SYNCHRONIZE",
    "THICK FAT",
    "TORRENT",
    "TRACE",
    "TRUANT",
    "VITAL SPIRIT",
    "VOLT ABSORB",
    "WATER ABSORB",
    "WATER VEIL",
    "WHITE SMOKE",
    "WONDER GUARD",
})

TRAINER_CLASS_NAMES: frozenset[str] = frozenset({
    "AQUA ADMIN",
    "AQUA LEADER",
    "ARENA TYCOON",
    "AROMA LADY",
    "BATTLE GIRL",
    "BEAUTY",
    "BIRD KEEPER",
    "BLACK BELT",
    "BUG CATCHER",
    "BUG MANIAC",
    "CAMPER",
    "CHAMPION",
    "COLLECTOR",
    "COOLTRAINER",
    "DOME ACE",
    "DRAGON TAMER",
    "ELITE FOUR",
    "EXPERT",
    "FACTORY HEAD",
    "FISHERMAN",
    "GENTLEMAN",
    "GUITARIST",
    "HEX MANIAC",
    "HIKER",
    "INTERVIEWER",
    "KINDLER",
    "LADY",
    "LASS",
    "LEADER",
    "MAGMA ADMIN",
    "MAGMA LEADER",
    "NINJA BOY",
    "OLD COUPLE",
    "PALACE MAVEN",
    "PARASOL LADY",
    "PICNICKER",
    "PIKE QUEEN",
    "PKMN BREEDER",
    "PKMN RANGER",
    "PKMN TRAINER",
    "POKéFAN",
    "POKéMANIAC",
    "PSYCHIC",
    "PYRAMID KING",
    "RICH BOY",
    "RUIN MANIAC",
    "SAILOR",
    "SALON MAIDEN",
    "SCHOOL KID",
    "SIS AND BRO",
    "SR. AND JR.",
    "SWIMMER♀",
    "SWIMMER♂",
    "TEAM AQUA",
    "TEAM MAGMA",
    "TRIATHLETE",
    "TUBER",
    "TWINS",
    "WINSTRATE",
    "YOUNG COUPLE",
    "YOUNGSTER",
})

TRAINER_NAMES: frozenset[str] = frozenset({
    "Aqua Admin Matt",
    "Aqua Admin Shelly",
    "Aqua Leader Archie",
    "Aroma Lady Daisy",
    "Battle Girl Cyndy",
    "Battle Girl Danielle",
    "Battle Girl Helene",
    "Battle Girl Jocelyn",
    "Battle Girl Laura",
    "Battle Girl Lilith",
    "Battle Girl Luna",
    "Battle Girl Reyna",
    "Battle Girl Vivian",
    "Beauty Bridget",
    "Beauty Jessica",
    "Beauty Johanna",
    "Beauty Thalia",
    "Beauty Tiffany",
    "Bird Keeper Aidan",
    "Bird Keeper Alex",
    "Bird Keeper Beck",
    "Bird Keeper Camden",
    "Bird Keeper Coby",
    "Bird Keeper Colin",
    "Bird Keeper Darius",
    "Bird Keeper Elijah",
    "Bird Keeper Hugh",
    "Bird Keeper Jared",
    "Bird Keeper Josue",
    "Bird Keeper Perry",
    "Bird Keeper Presley",
    "Bird Keeper Robert",
    "Black Belt Atsushi",
    "Black Belt Cristian",
    "Black Belt Daisuke",
    "Black Belt Hawk",
    "Black Belt Hitoshi",
    "Black Belt Kiyo",
    "Black Belt Koichi",
    "Black Belt Nob",
    "Black Belt Rhett",
    "Black Belt Takao",
    "Black Belt Zander",
    "Bug Catcher Davis",
    "Bug Catcher Doug",
    "Bug Catcher Greg",
    "Bug Catcher Jose",
    "Bug Catcher Kent",
    "Bug Catcher Lyle",
    "Bug Catcher Rick",
    "Bug Maniac Brent",
    "Bug Maniac James",
    "Bug Maniac Jeffrey",
    "Bug Maniac Taylor",
    "Camper Beau",
    "Camper Branden",
    "Camper Drew",
    "Camper Ethan",
    "Camper Flint",
    "Camper Gavi",
    "Camper Lawrence",
    "Camper Merc",
    "Camper Travis",
    "Camper Tyron",
    "Champion Wallace",
    "Collector Edwin",
    "Collector Hector",
    "Collector John",
    "Cool Trainer Alexa",
    "Cool Trainer Alexia",
    "Cool Trainer Berke",
    "Cool Trainer Brooke",
    "Cool Trainer Carolina",
    "Cool Trainer Caroline",
    "Cool Trainer Cristin",
    "Cool Trainer Darcy",
    "Cool Trainer Edgar",
    "Cool Trainer Felix",
    "Cool Trainer George",
    "Cool Trainer Gerald",
    "Cool Trainer Gian",
    "Cool Trainer Gustavo",
    "Cool Trainer Halle",
    "Cool Trainer Hope",
    "Cool Trainer Jennifer",
    "Cool Trainer Jody",
    "Cool Trainer Jonathan",
    "Cool Trainer Julie",
    "Cool Trainer Katelynn",
    "Cool Trainer Marley",
    "Cool Trainer Mary",
    "Cool Trainer Michelle",
    "Cool Trainer Parker",
    "Cool Trainer Quincy",
    "Cool Trainer Randall",
    "Cool Trainer Ruben",
    "Cool Trainer Samuel",
    "Cool Trainer Shannon",
    "Cool Trainer Specter",
    "Cool Trainer Tammy",
    "Cool Trainer Warren",
    "Cool Trainer Wendy",
    "Cool Trainer Wilton",
    "Dragon Tamer Aaron",
    "Dragon Tamer Nicolas",
    "Dumbass Soupercell",
    "Elite Four Drake",
    "Elite Four Glacia",
    "Elite Four Phoebe",
    "Elite Four Sidney",
    "Expert Donald",
    "Expert Kevin",
    "Expert Makayla",
    "Expert Mollie",
    "Expert Nancy",
    "Expert Paxton",
    "Expert Timothy",
    "Fisherman Andrew",
    "Fisherman Barny",
    "Fisherman Bill",
    "Fisherman Carter",
    "Fisherman Claude",
    "Fisherman Dale",
    "Fisherman Darian",
    "Fisherman Elliot",
    "Fisherman Henry",
    "Fisherman Ivan",
    "Fisherman Jonah",
    "Fisherman Kai",
    "Fisherman Nolan",
    "Fisherman Phil",
    "Fisherman Roger",
    "Fisherman Ronald",
    "Fisherman Wade",
    "Fisherman Wayne",
    "Gentleman Clifford",
    "Gentleman Walter",
    "Guitarist Brian",
    "Guitarist Dalton",
    "Guitarist Fernando",
    "Guitarist Kirk",
    "Guitarist Shawn",
    "Hex Maniac Gongas",
    "Hex Maniac Kathleen",
    "Hex Maniac Leah",
    "Hex Maniac Tasha",
    "Hex Maniac Valerie",
    "Hiker Brice",
    "Hiker Clark",
    "Hiker Devan",
    "Hiker Eli",
    "Hiker Eric",
    "Hiker Lenny",
    "Hiker Lucas",
    "Hiker Marc",
    "Hiker Mike",
    "Hiker Trent",
    "Interviewer Gabby & Ty",
    "Kindler Axle",
    "Kindler Bernie",
    "Kindler Bryant",
    "Kindler Cole",
    "Kindler Hayden",
    "Kindler Jace",
    "Kindler Jeff",
    "Kindler Keegan",
    "Lady Brianna",
    "Lady Cindy",
    "Lady Daphne",
    "Lady Sarah",
    "Lass Andrea",
    "Lass Crissy",
    "Lass Haley",
    "Lass Janice",
    "Lass Pearl",
    "Lass Tiana",
    "Leader Brawly",
    "Leader Flannery",
    "Leader Juan",
    "Leader Liza",
    "Leader Norman",
    "Leader Roxanne",
    "Leader Tate",
    "Leader Wattson",
    "Leader Winona",
    "Magma Admin Courtney",
    "Magma Admin Tabitha",
    "Magma Leader Maxie",
    "Ninja Boy Gren",
    "Ninja Boy Jack",
    "Ninja Boy Jinra",
    "Ninja Boy Jonas",
    "Ninja Boy Keigo",
    "Ninja Boy Lao",
    "Ninja Boy Lung",
    "Ninja Boy Riley",
    "Ninja Boy Takashi",
    "Ninja Boy Yasu",
    "Old Couple John & Jay",
    "Parasol Lady Angelica",
    "Parasol Lady Clarissa",
    "Parasol Lady Koko",
    "Parasol Lady Madeline",
    "Picnicker Angelina",
    "Picnicker Ashley",
    "Picnicker Bianca",
    "Picnicker Carol",
    "Picnicker Charlotte",
    "Picnicker Diana",
    "Picnicker Irene",
    "Picnicker Sophie",
    "Pokemon Breeder Corgi",
    "Pokemon Breeder Gabrielle",
    "Pokemon Breeder Isaac",
    "Pokemon Breeder Lydia",
    "Pokemon Breeder Myles",
    "Pokemon Breeder Pat",
    "Pokemon Ranger Catherine",
    "Pokemon Ranger Jackson",
    "Pokemon Ranger Jenna",
    "Pokemon Ranger Lorenzo",
    "Pokemon Ranger Lydian",
    "Pokemon Trainer Chelle",
    "Pokemon Trainer May",
    "Pokemon Trainer Steven",
    "Pokemon Trainer Wally",
    "Pokéfan Bethany",
    "Pokéfan Isabel",
    "Pokéfan Miguel",
    "Pokéfan Vanessa",
    "Pokémaniac Hambino",
    "Pokémaniac Mark",
    "Pokémaniac Steve",
    "Pokémaniac Wyatt",
    "Psychic Alix",
    "Psychic Blake",
    "Psychic Brandi",
    "Psychic Cameron",
    "Psychic Cedric",
    "Psychic Edward",
    "Psychic Hannah",
    "Psychic Jacki",
    "Psychic Jaclyn",
    "Psychic Kayla",
    "Psychic Marlene",
    "Psychic Preston",
    "Psychic Virgil",
    "Psychic William",
    "Rich Boy Braw",
    "Rich Boy Dawson",
    "Rich Boy Santos",
    "Rich Boy Winston",
    "Ruin Maniac Bryan",
    "Ruin Maniac Chip",
    "Ruin Maniac Foster",
    "Ruin Maniac Garrison",
    "Ruin Maniac Georgie",
    "Ruin Maniac Rigger",
    "Sailor Brenden",
    "Sailor Duncan",
    "Sailor Dwayne",
    "Sailor Edmond",
    "Sailor Ernest",
    "Sailor Hudson",
    "Sailor Kelvin",
    "School Kid Jerry",
    "School Kid Karen",
    "Sis And Bro Lila & Roy",
    "Sis And Bro Lisa & Ray",
    "Sis And Bro Reli & Ian",
    "Sr. And Jr. Anna & Meg",
    "Sr. And Jr. Kim & Iris",
    "Sr. And Jr. Tyra & Ivy",
    "Swimmer♀ Alice",
    "Swimmer♀ Beth",
    "Swimmer♀ Beverly",
    "Swimmer♀ Brenda",
    "Swimmer♀ Carlee",
    "Swimmer♀ Dana",
    "Swimmer♀ Debra",
    "Swimmer♀ Denise",
    "Swimmer♀ Grace",
    "Swimmer♀ Imani",
    "Swimmer♀ Kara",
    "Swimmer♀ Katie",
    "Swimmer♀ Kyla",
    "Swimmer♀ Laurel",
    "Swimmer♀ Missy",
    "Swimmer♀ Nikki",
    "Swimmer♀ Rose",
    "Swimmer♀ Sharon",
    "Swimmer♀ Sienna",
    "Swimmer♀ Susie",
    "Swimmer♀ Tanya",
    "Swimmer♀ Tara",
    "Swimmer♀ Tisha",
    "Swimmer♂ Barry",
    "Swimmer♂ Chad",
    "Swimmer♂ Clarence",
    "Swimmer♂ Cranberry",
    "Swimmer♂ Darrin",
    "Swimmer♂ David",
    "Swimmer♂ Dean",
    "Swimmer♂ Dominik",
    "Swimmer♂ Douglas",
    "Swimmer♂ Franklin",
    "Swimmer♂ Herman",
    "Swimmer♂ Jaiden",
    "Swimmer♂ Jerome",
    "Swimmer♂ Leonardo",
    "Swimmer♂ Luis",
    "Swimmer♂ Matthew",
    "Swimmer♂ Nolen",
    "Swimmer♂ Reed",
    "Swimmer♂ Richard",
    "Swimmer♂ Rodney",
    "Swimmer♂ Roland",
    "Swimmer♂ Santiago",
    "Swimmer♂ Stan",
    "Swimmer♂ Tony",
    "Swimmer♂ Zappator",
    "Team Aqua Grunt",
    "Team Aqua Grunt Jazz",
    "Team Magma Grunt",
    "Team Magma Grunt Zerk",
    "Triathlete Abigail",
    "Triathlete Alyssa",
    "Triathlete Anthony",
    "Triathlete Aubrey",
    "Triathlete Benjamin",
    "Triathlete Camron",
    "Triathlete Chase",
    "Triathlete Darren",
    "Triathlete Dylan",
    "Triathlete Isabella",
    "Triathlete Isaiah",
    "Triathlete Isobel",
    "Triathlete Jacob",
    "Triathlete Jasmine",
    "Triathlete Julio",
    "Triathlete Katelyn",
    "Triathlete Kyra",
    "Triathlete Maria",
    "Triathlete Mikey",
    "Triathlete Pablo",
    "Triathlete Xayah",
    "Tuber Austina",
    "Tuber Chandler",
    "Tuber Charlie",
    "Tuber Gwen",
    "Tuber Hailey",
    "Tuber Lola",
    "Tuber Ricky",
    "Tuber Simon",
    "Twins Amy & Liv",
    "Twins Gina & Mia",
    "Twins Miu & Yuki",
    "Twins Tori & Tia",
    "Winstrate Vicky",
    "Winstrate Victor",
    "Winstrate Victoria",
    "Winstrate Vito",
    "Winstrate Vivi",
    "Young Couple Brian&Casey",
    "Young Couple Dez & Luke",
    "Young Couple Kira & Dan",
    "Young Couple Mel & Paul",
    "Youngster Allen",
    "Youngster Ben",
    "Youngster Calvin",
    "Youngster Demetrius",
    "Youngster Jaylen",
    "Youngster Joey",
    "Youngster Josh",
    "Youngster Tommy",
})
