# C++ header codegen for NuzlockeAI data tables (C0.3).
# Reads src/data/* in-process (single source of truth) and emits deterministic
# C++ headers into cpp/generated/. Run with --check to verify committed headers
# are not stale vs the Python source; exit non-zero if any file drifted.
import argparse
import os
import shutil
import sys
import tempfile
from typing import Optional

# Allow running from repo root or SCRIPTS/
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from liveplay.data.species import SPECIES_DATA, SPECIES_WEIGHTS, Species, SpeciesData
from liveplay.data.moves import (MOVE_DATA, Move, MoveData, SecondaryEffect, MoveCategory, MoveTarget, MoveTag,
    PROTECT_MOVES, WEATHER_RECOVERY_MOVES, RECOVERY_MOVE_SET, PARALYSIS_MOVES, POISON_INFLICT_MOVES,
    SPEED_SETUP_MOVES, OFFENSIVE_SETUP_MOVES, DEFENSIVE_SETUP_MOVES, TERRAIN_MOVES)
from liveplay.data.items import ITEM_DATA, Item, ItemData
from liveplay.data.types import Type, _TYPE_CHART
from liveplay.data.natures import NATURE_DATA, Nature, NatureData, Stat
from liveplay.data.status import Status
from liveplay.data.growth_rate import GrowthRate
from liveplay.data.abilities import Ability
from liveplay.state.battle import WeatherEnum

_CPP_GENERATED = os.path.join(_REPO_ROOT, "engine", "generated")

# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _fmt_float(v: float) -> str:
    """Format float with enough precision to round-trip; no trailing noise."""
    # Use repr-style but strip unnecessary trailing zeros after 6 decimal places
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    if "." not in s:
        s += ".0"
    return s


def _species_weight_literal(species: Species) -> str:
    """Shortest round-trip float literal for a species' authoritative weight.

    Fail loud: every species in SPECIES_DATA must have an entry in SPECIES_WEIGHTS
    (no silent 0.0 default). repr() gives the shortest string that round-trips.
    """
    if species not in SPECIES_WEIGHTS:
        raise KeyError(
            f"SPECIES_WEIGHTS has no weight for {species.name} (value {species.value}); "
            f"regenerate via SCRIPTS/build_species_weights.py"
        )
    return repr(float(SPECIES_WEIGHTS[species]))


def _fmt_optional_int(v: Optional[int]) -> str:
    return str(v) if v is not None else "-1"


def _fmt_optional_float(v: Optional[float]) -> str:
    return _fmt_float(v) if v is not None else "-1.0"


def _fmt_optional_stat(v: Optional[Stat]) -> str:
    return str(v.value) if v is not None else "-1"


def _header_guard(name: str) -> str:
    return f"NUZLOCKE_{name.upper().replace('.', '_')}_H"


def _file_header(guard: str, description: str) -> str:
    return (
        f"// AUTO-GENERATED by SCRIPTS/gen_cpp_data.py — DO NOT EDIT.\n"
        f"// Source of truth: src/data/. Re-run gen_cpp_data.py to update.\n"
        f"// {description}\n"
        f"#pragma once\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n"
        f"\n"
        f"#include <cstdint>\n"
    )


def _file_footer(guard: str) -> str:
    return f"\n#endif // {guard}\n"


# ---------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------

def _emit_types_enum() -> str:
    """Emit Type enum so other headers can reference it."""
    lines = ["enum class Type : int8_t {"]
    for t in sorted(Type, key=lambda x: x.value):
        lines.append(f"    {t.name} = {t.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_status_enum() -> str:
    lines = ["enum class Status : int8_t {"]
    for s in sorted(Status, key=lambda x: x.value):
        lines.append(f"    {s.name} = {s.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_growth_rate_enum() -> str:
    lines = ["enum class GrowthRate : int8_t {"]
    for g in sorted(GrowthRate, key=lambda x: x.value):
        lines.append(f"    {g.name} = {g.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_stat_enum() -> str:
    lines = ["enum class Stat : int8_t {"]
    for s in sorted(Stat, key=lambda x: x.value):
        lines.append(f"    {s.name} = {s.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_move_category_enum() -> str:
    lines = ["enum class MoveCategory : int8_t {"]
    for c in sorted(MoveCategory, key=lambda x: x.value):
        lines.append(f"    {c.name} = {c.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_move_target_enum() -> str:
    lines = ["enum class MoveTarget : int8_t {"]
    for t in sorted(MoveTarget, key=lambda x: x.value):
        lines.append(f"    {t.name} = {t.value},")
    lines.append("};")
    return "\n".join(lines)


def _emit_nature_enum() -> str:
    lines = ["enum class Nature : int8_t {"]
    for n in sorted(Nature, key=lambda x: x.value):
        lines.append(f"    {n.name} = {n.value},")
    lines.append("};")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# species_data.h
# ---------------------------------------------------------------------------

def _emit_species_data_h() -> str:
    guard = _header_guard("species_data")
    lines = [
        _file_header(guard, f"SpeciesData table: {len(SPECIES_DATA)} entries."),
        _emit_types_enum(),
        _emit_growth_rate_enum(),
        "",
        "struct SpeciesData {",
        "    int8_t  type1;        // Type enum value",
        "    int8_t  type2;        // Type enum value; -1 if mono-type",
        "    uint8_t base_hp;",
        "    uint8_t base_atk;",
        "    uint8_t base_def;",
        "    uint8_t base_spa;",
        "    uint8_t base_spd;",
        "    uint8_t base_spe;",
        "    float   male_ratio;   // -1.0 = genderless",
        "    double  weight_kg;",
        "    int8_t  growth_rate;  // GrowthRate enum value",
        "    int16_t exp_yield;",
        "    int32_t species_id;   // Species enum value (IntEnum)",
        "};",
        "",
        f"// Table of {len(SPECIES_DATA)} species, sorted by enum integer value.",
        f"static const SpeciesData SPECIES_TABLE[{len(SPECIES_DATA)}] = {{",
    ]

    for species in sorted(SPECIES_DATA.keys(), key=lambda s: s.value):
        d: SpeciesData = SPECIES_DATA[species]
        type1 = d.types[0].value
        type2 = d.types[1].value if len(d.types) > 1 else -1
        male_ratio = _fmt_optional_float(d.male_ratio)
        lines.append(
            f"    {{ {type1}, {type2}, {d.base_hp}, {d.base_atk}, {d.base_def},"
            f" {d.base_spa}, {d.base_spd}, {d.base_spe},"
            f" {male_ratio}f, {_species_weight_literal(species)},"
            f" {d.growth_rate.value}, {d.exp_yield}, {species.value} }}, // entry {species.name}"
        )

    lines.append("};")
    lines.append(_file_footer(guard))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# move_data.h
# ---------------------------------------------------------------------------

_MAX_SECONDARY_STAT_CHANGES = 5
_MAX_SELF_STAT_CHANGES = 3


def _validate_stat_change_lengths() -> None:
    """Fail loud if any move exceeds the assumed max array sizes."""
    for move, d in MOVE_DATA.items():
        for sec in (d.secondary, d.secondary2):
            if sec is not None and len(sec.stat_changes) > _MAX_SECONDARY_STAT_CHANGES:
                raise ValueError(
                    f"{move.name} secondary stat_changes length {len(sec.stat_changes)}"
                    f" exceeds MAX_SECONDARY_STAT_CHANGES={_MAX_SECONDARY_STAT_CHANGES}"
                )
        if len(d.self_stat_changes) > _MAX_SELF_STAT_CHANGES:
            raise ValueError(
                f"{move.name} self_stat_changes length {len(d.self_stat_changes)}"
                f" exceeds MAX_SELF_STAT_CHANGES={_MAX_SELF_STAT_CHANGES}"
            )


def _fmt_stat_changes_array(stat_changes: tuple, max_n: int) -> str:
    """Format a fixed-size inline array of (stat_idx, delta, self_flag) triples, zero-padded."""
    entries = []
    for i in range(max_n):
        if i < len(stat_changes):
            entry = stat_changes[i]
            idx = entry[0]
            delta = entry[1]
            self_flag = 1 if (len(entry) > 2 and entry[2]) else 0
            entries.append(f"{{ {idx}, {delta}, {self_flag} }}")
        else:
            entries.append("{ 0, 0, 0 }")
    return "{ " + ", ".join(entries) + " }"


def _fmt_self_stat_changes_array(self_stat_changes: tuple, max_n: int) -> str:
    """Format a fixed-size inline array of (stat_idx, delta) pairs, zero-padded."""
    entries = []
    for i in range(max_n):
        if i < len(self_stat_changes):
            entry = self_stat_changes[i]
            entries.append(f"{{ {entry[0]}, {entry[1]} }}")
        else:
            entries.append("{ 0, 0 }")
    return "{ " + ", ".join(entries) + " }"


def _fmt_secondary(sec: Optional[SecondaryEffect]) -> str:
    """Format a SecondaryEffect as a C struct literal with full inline stat_changes array."""
    if sec is None:
        empty_array = _fmt_stat_changes_array((), _MAX_SECONDARY_STAT_CHANGES)
        return f"{{ 0, -1, false, 0, false, false, 0, {empty_array} }}"
    status_val = sec.status.value if sec.status is not None else -1
    volatile_flag = 1 if sec.volatile == "confused" else 0
    stat_array = _fmt_stat_changes_array(sec.stat_changes, _MAX_SECONDARY_STAT_CHANGES)
    return (
        f"{{ {sec.chance}, {status_val}, {'true' if sec.flinch else 'false'},"
        f" {volatile_flag}, {'true' if sec.status is not None else 'false'},"
        f" {'true' if sec.volatile is not None else 'false'},"
        f" {len(sec.stat_changes)}, {stat_array} }}"
    )


def _emit_move_data_h() -> str:
    _validate_stat_change_lengths()
    guard = _header_guard("move_data")
    max_sec = _MAX_SECONDARY_STAT_CHANGES
    max_self = _MAX_SELF_STAT_CHANGES
    lines = [
        _file_header(guard, f"MoveData table: {len(MOVE_DATA)} entries."),
        _emit_types_enum(),
        _emit_status_enum(),
        _emit_move_category_enum(),
        _emit_move_target_enum(),
        "",
        f"static const int MAX_SECONDARY_STAT_CHANGES = {max_sec};",
        f"static const int MAX_SELF_STAT_CHANGES = {max_self};",
        "",
        "// One stat change entry: stat_idx (Stat enum value), delta, self_flag (1=self, 0=target).",
        "struct StatChangeEntry {",
        "    int8_t stat_idx;",
        "    int8_t delta;",
        "    int8_t self_flag;",
        "};",
        "",
        "// Secondary effect. All stat_changes entries emitted inline; unused slots zeroed.",
        "struct SecondaryEffect {",
        "    int8_t  chance;               // 0-100",
        "    int8_t  status;               // Status enum value; -1 = none",
        "    bool    flinch;",
        "    int8_t  volatile_confused;    // 1 = inflicts confusion",
        "    bool    has_status;",
        "    bool    has_volatile;",
        f"    int8_t  num_stat_changes;",
        f"    StatChangeEntry stat_changes[{max_sec}];",
        "};",
        "",
        "// One self-stat-change entry applied to user after damage; not suppressed by Sheer Force.",
        "struct SelfStatChangeEntry {",
        "    int8_t stat_idx;",
        "    int8_t delta;",
        "};",
        "",
        "struct MoveData {",
        "    int8_t  move_type;    // Type enum value",
        "    int8_t  category;     // MoveCategory",
        "    uint8_t base_power;",
        "    int8_t  accuracy;     // -1 = always hits",
        "    uint8_t pp;",
        "    int8_t  priority;",
        "    int8_t  target;       // MoveTarget",
        "    int32_t tags;         // MoveTag bitmask",
        "    int8_t  min_hits;",
        "    int8_t  max_hits;",
        "    int8_t  crit_boost;",
        "    int8_t  drain_num;    // drain numerator; -1 = none",
        "    int8_t  drain_den;    // drain denominator",
        "    int8_t  recoil_num;   // recoil numerator; -1 = none",
        "    int8_t  recoil_den;",
        "    SecondaryEffect secondary;",
        "    SecondaryEffect secondary2;",
        f"    int8_t  num_self_stat_changes;",
        f"    SelfStatChangeEntry self_stat_changes[{max_self}];",
        "    int32_t move_id;      // Move enum value",
        "};",
        "",
        f"// Table of {len(MOVE_DATA)} moves, sorted by enum integer value.",
        f"static const MoveData MOVE_TABLE[{len(MOVE_DATA)}] = {{",
    ]

    for move in sorted(MOVE_DATA.keys(), key=lambda m: m.value):
        d: MoveData = MOVE_DATA[move]
        accuracy = _fmt_optional_int(d.accuracy)
        drain_num = d.drain[0] if d.drain else -1
        drain_den = d.drain[1] if d.drain else 0
        recoil_num = d.recoil[0] if d.recoil else -1
        recoil_den = d.recoil[1] if d.recoil else 0
        sec = _fmt_secondary(d.secondary)
        sec2 = _fmt_secondary(d.secondary2)
        self_array = _fmt_self_stat_changes_array(d.self_stat_changes, max_self)
        lines.append(
            f"    {{ {d.move_type.value}, {d.category.value}, {d.base_power},"
            f" {accuracy}, {d.pp}, {d.priority}, {d.target.value}, {int(d.tags)},"
            f" {d.min_hits}, {d.max_hits}, {d.crit_boost},"
            f" {drain_num}, {drain_den}, {recoil_num}, {recoil_den},"
            f" {sec}, {sec2}, {len(d.self_stat_changes)}, {self_array}, {move.value} }},"
            f" // entry {move.name}"
        )

    lines.append("};")
    lines.append(_file_footer(guard))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# item_data.h
# ---------------------------------------------------------------------------

def _escape_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _emit_item_data_h() -> str:
    guard = _header_guard("item_data")
    lines = [
        _file_header(guard, f"ItemData table: {len(ITEM_DATA)} entries."),
        "",
        "struct ItemData {",
        "    const char* name;   // display name",
        "    int32_t     item_id; // Item enum value",
        "};",
        "",
        f"// Table of {len(ITEM_DATA)} items, sorted by enum integer value.",
        f"static const ItemData ITEM_TABLE[{len(ITEM_DATA)}] = {{",
    ]

    for item in sorted(ITEM_DATA.keys(), key=lambda i: i.value):
        d: ItemData = ITEM_DATA[item]
        lines.append(
            f'    {{ "{_escape_str(d.name)}", {item.value} }}, // entry {item.name}'
        )

    lines.append("};")
    lines.append(_file_footer(guard))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# type_chart.h
# ---------------------------------------------------------------------------

def _emit_type_chart_h() -> str:
    guard = _header_guard("type_chart")
    n = len(_TYPE_CHART)
    lines = [
        _file_header(guard, f"Type effectiveness chart: {n}x{n} float array [atk][def]."),
        _emit_types_enum(),
        "",
        f"// TYPE_CHART[attacking][defending] -> multiplier (0.0, 0.5, 1.0, or 2.0).",
        f"// Index 18 = TYPELESS: always 1.0.",
        f"static const float TYPE_CHART[{n}][{n}] = {{",
    ]

    for atk_idx in range(n):
        row_vals = ", ".join(_fmt_float(v) + "f" for v in _TYPE_CHART[atk_idx])
        atk_name = Type(atk_idx).name if atk_idx < 19 else "?"
        lines.append(f"    {{ {row_vals} }},  // {atk_name}")

    lines.append("};")
    lines.append(_file_footer(guard))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# nature_data.h
# ---------------------------------------------------------------------------

def _emit_nature_data_h() -> str:
    guard = _header_guard("nature_data")
    lines = [
        _file_header(guard, f"NatureData table: {len(NATURE_DATA)} entries."),
        _emit_stat_enum(),
        _emit_nature_enum(),
        "",
        "struct NatureData {",
        "    int8_t boosted;  // Stat enum value; -1 = neutral",
        "    int8_t lowered;  // Stat enum value; -1 = neutral",
        "    int8_t nature_id; // Nature enum value",
        "};",
        "",
        f"// Table of {len(NATURE_DATA)} natures, sorted by enum integer value.",
        f"static const NatureData NATURE_TABLE[{len(NATURE_DATA)}] = {{",
    ]

    for nature in sorted(NATURE_DATA.keys(), key=lambda n: n.value):
        d: NatureData = NATURE_DATA[nature]
        boosted = _fmt_optional_stat(d.boosted)
        lowered = _fmt_optional_stat(d.lowered)
        lines.append(
            f"    {{ {boosted}, {lowered}, {nature.value} }}, // entry {nature.name}"
        )

    lines.append("};")
    lines.append(_file_footer(guard))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# status.h  (simple enum header)
# ---------------------------------------------------------------------------

def _emit_status_h() -> str:
    guard = _header_guard("status")
    lines = [
        _file_header(guard, "Status enum for non-volatile conditions."),
        _emit_status_enum(),
        _file_footer(guard),
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# growth_rate.h  (simple enum header)
# ---------------------------------------------------------------------------

def _emit_growth_rate_h() -> str:
    guard = _header_guard("growth_rate")
    lines = [
        _file_header(guard, "GrowthRate enum for EXP curve identifiers."),
        _emit_growth_rate_enum(),
        _file_footer(guard),
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ai_move_sets.h  (move/ability classification sets for ai_scorer)
# ---------------------------------------------------------------------------

def _emit_ai_move_sets_h() -> str:
    """Emit move and ability classification sets used by the AI scorer.

    Emits frozensets from moves.py and ai.py as constexpr arrays + counts.
    Also emits _WEATHER_MOVE_TO_WEATHER as parallel move_id/weather int arrays.
    Includes ai_set_contains() inline helper for linear scan membership tests.
    """
    import sys as _sys
    _AI_SRC = "/home/Fracture/PycharmProjects/NuzlockeAI"
    if _AI_SRC not in _sys.path:
        _sys.path.insert(0, _AI_SRC)
    from src.ai import (
        _MOXIE_ABILITIES, _HIGH_CRIT_MOVES, _SPEED_REDUCTION_MOVES,
        _STAT_REDUCTION_DAMAGE_MOVES, _STAT_REDUCTION_ABILITIES,
        _ROLE_PLAY_VALUABLE_ABILITIES, _UNAWARE_SETUP_EXCEPTIONS,
        _WEATHER_MOVE_TO_WEATHER,
    )

    guard = _header_guard("ai_move_sets")
    lines = [
        "// AUTO-GENERATED by SCRIPTS/gen_cpp_data.py — DO NOT EDIT.\n"
        "// Source of truth: src/data/moves.py + src/ai.py. Re-run gen_cpp_data.py to update.\n"
        "// Move and ability classification sets for the AI scorer (ai_scorer.cpp).\n"
        "#pragma once\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n"
        "\n"
        "#include <cstdint>\n",
    ]

    def emit_int_set(name: str, values, comment_map=None) -> list[str]:
        """Emit a constexpr int32_t array + count for a frozenset of enum values."""
        sorted_vals = sorted(values, key=lambda x: int(x))
        out = [f"static constexpr int32_t {name}[] = {{"]
        for v in sorted_vals:
            comment = f"  // {comment_map(v)}" if comment_map else ""
            out.append(f"    {int(v)},{comment}")
        out.append("};")
        out.append(f"static constexpr int N_{name} = {len(sorted_vals)};")
        return out

    # --- from moves.py ---
    lines += emit_int_set("PROTECT_MOVES", PROTECT_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("WEATHER_RECOVERY_MOVES", WEATHER_RECOVERY_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("RECOVERY_MOVE_SET", RECOVERY_MOVE_SET,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("PARALYSIS_MOVES", PARALYSIS_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("POISON_INFLICT_MOVES", POISON_INFLICT_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("SPEED_SETUP_MOVES", SPEED_SETUP_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("OFFENSIVE_SETUP_MOVES", OFFENSIVE_SETUP_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("DEFENSIVE_SETUP_MOVES", DEFENSIVE_SETUP_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("TERRAIN_MOVES", TERRAIN_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")

    # --- from ai.py ---
    lines += emit_int_set("MOXIE_ABILITIES", _MOXIE_ABILITIES,
                          comment_map=lambda v: Ability(v).name)
    lines.append("")
    lines += emit_int_set("HIGH_CRIT_MOVES", _HIGH_CRIT_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("SPEED_REDUCTION_MOVES", _SPEED_REDUCTION_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("STAT_REDUCTION_DAMAGE_MOVES", _STAT_REDUCTION_DAMAGE_MOVES,
                          comment_map=lambda v: Move(v).name)
    lines.append("")
    lines += emit_int_set("STAT_REDUCTION_ABILITIES", _STAT_REDUCTION_ABILITIES,
                          comment_map=lambda v: Ability(v).name)
    lines.append("")
    lines += emit_int_set("ROLE_PLAY_VALUABLE_ABILITIES", _ROLE_PLAY_VALUABLE_ABILITIES,
                          comment_map=lambda v: Ability(v).name)
    lines.append("")
    lines += emit_int_set("UNAWARE_SETUP_EXCEPTIONS", _UNAWARE_SETUP_EXCEPTIONS,
                          comment_map=lambda v: Move(v).name)
    lines.append("")

    # _WEATHER_MOVE_TO_WEATHER: emit as parallel move_id and weather_id arrays
    sorted_wm2w = sorted(_WEATHER_MOVE_TO_WEATHER.items(), key=lambda kv: int(kv[0]))
    lines.append("// _WEATHER_MOVE_TO_WEATHER: parallel arrays (move_id → weather enum int)")
    lines.append(f"static constexpr int32_t WEATHER_MOVE_IDS[] = {{")
    for mv, _ in sorted_wm2w:
        lines.append(f"    {int(mv)},  // {Move(mv).name}")
    lines.append("};")
    lines.append(f"static constexpr int32_t WEATHER_MOVE_WEATHERS[] = {{")
    for mv, we in sorted_wm2w:
        lines.append(f"    {int(we)},  // {WeatherEnum(we).name}")
    lines.append("};")
    lines.append(f"static constexpr int N_WEATHER_MOVES = {len(sorted_wm2w)};")
    lines.append("")

    # Inline helper for linear-scan membership test
    lines += [
        "// Linear-scan membership test for the arrays above.",
        "inline bool ai_set_contains(const int32_t* arr, int n, int32_t v) {",
        "    for (int i = 0; i < n; ++i) if (arr[i] == v) return true;",
        "    return false;",
        "}",
        "",
        f"#endif // {guard}",
    ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API: generate(out_dir) and CLI
# ---------------------------------------------------------------------------

_EMITTERS: dict[str, callable] = {
    "species_data.h": _emit_species_data_h,
    "move_data.h": _emit_move_data_h,
    "item_data.h": _emit_item_data_h,
    "type_chart.h": _emit_type_chart_h,
    "nature_data.h": _emit_nature_data_h,
    "status.h": _emit_status_h,
    "growth_rate.h": _emit_growth_rate_h,
    "ai_move_sets.h": _emit_ai_move_sets_h,
}


def generate(out_dir: str) -> None:
    """Write all C++ headers to out_dir. Creates the directory if absent."""
    os.makedirs(out_dir, exist_ok=True)
    for filename, emitter in sorted(_EMITTERS.items()):
        content = emitter()
        path = os.path.join(out_dir, filename)
        with open(path, "w", newline="\n") as f:
            f.write(content)


def _check(committed_dir: str) -> list[str]:
    """Regenerate into a temp dir and compare against committed_dir.

    Returns a list of filenames that differ (empty means up-to-date)."""
    with tempfile.TemporaryDirectory() as tmp:
        generate(tmp)
        drifted = []
        for filename in sorted(_EMITTERS.keys()):
            fresh_path = os.path.join(tmp, filename)
            committed_path = os.path.join(committed_dir, filename)
            if not os.path.exists(committed_path):
                drifted.append(filename)
                continue
            fresh = open(fresh_path, "rb").read()
            committed = open(committed_path, "rb").read()
            if fresh != committed:
                drifted.append(filename)
        return drifted


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate C++ data headers from Python src/data/ tables."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify committed headers are up-to-date; exit non-zero if stale.",
    )
    parser.add_argument(
        "--check-dir",
        default=_CPP_GENERATED,
        metavar="DIR",
        help="Directory to compare against during --check (default: cpp/generated/).",
    )
    parser.add_argument(
        "--out",
        default=_CPP_GENERATED,
        metavar="DIR",
        help="Output directory for generated headers (default: cpp/generated/).",
    )
    args = parser.parse_args()

    if args.check:
        drifted = _check(args.check_dir)
        if drifted:
            print("ERROR: the following committed headers are stale vs Python source:")
            for f in drifted:
                print(f"  {f}")
            print("Re-run: python SCRIPTS/gen_cpp_data.py")
            sys.exit(1)
        else:
            print("OK: all headers are up-to-date.")
    else:
        generate(args.out)
        print(f"Generated {len(_EMITTERS)} headers into {args.out}")


if __name__ == "__main__":
    main()
