// Enum int-value constants for the effects/post_hit port (C1.4).
// Values mirror Python IntEnum/IntFlag definitions exactly; verified against src/data and src/state.
#pragma once
#ifndef NUZLOCKE_EFFECTS_CONSTS_H
#define NUZLOCKE_EFFECTS_CONSTS_H

#include <cstdint>

namespace eff {

// --- Abilities ---
constexpr int32_t AB_NONE = 0, AB_MAGIC_GUARD = 98, AB_REGENERATOR = 144, AB_NATURAL_CURE = 30,
    AB_SAP_SIPPER = 157, AB_FLASH_FIRE = 18, AB_INFILTRATOR = 151, AB_CORROSION = 212,
    AB_IMMUNITY = 17, AB_WATER_VEIL = 41, AB_WATER_BUBBLE = 199, AB_MAGMA_ARMOR = 40,
    AB_INSOMNIA = 15, AB_VITAL_SPIRIT = 72, AB_LIMBER = 7, AB_SWEET_VEIL = 175,
    AB_PASTEL_VEIL = 257, AB_FLOWER_VEIL = 166, AB_LEAF_GUARD = 102, AB_COMATOSE = 213,
    AB_CONTRARY = 126, AB_HYPER_CUTTER = 52, AB_CLEAR_BODY = 29, AB_WHITE_SMOKE = 73,
    AB_FULL_METAL_BODY = 230, AB_KEEN_EYE = 51, AB_SIMPLE = 86, AB_DEFIANT = 128,
    AB_COMPETITIVE = 172, AB_UNBURDEN = 84, AB_SYNCHRONIZE = 28, AB_OWN_TEMPO = 20,
    AB_AIR_LOCK = 76, AB_CLOUD_NINE = 13, AB_LEVITATE = 26,
    AB_OBLIVIOUS = 12, AB_AROMA_VEIL = 165, AB_LIQUID_OOZE = 64,
    AB_STICKY_HOLD = 60, AB_TRUANT = 54, AB_SUCTION_CUPS = 21,
    AB_INNER_FOCUS = 39, AB_STEADFAST = 80;

// Entry-effect abilities (C1.7d U4.5: _apply_entry_effects)
constexpr int32_t AB_INTIMIDATE = 22, AB_DRIZZLE = 2, AB_PRIMORDIAL_SEA = 189, AB_DROUGHT = 70,
    AB_DESOLATE_LAND = 190, AB_SAND_STREAM = 45, AB_SNOW_WARNING = 117,
    AB_ELECTRIC_SURGE = 226, AB_GRASSY_SURGE = 229, AB_PSYCHIC_SURGE = 227, AB_MISTY_SURGE = 228,
    AB_TERAVOLT = 164, AB_TURBOBLAZE = 163, AB_UNNERVE = 127, AB_AS_ONE_GLASTRIER = 266,
    AB_AS_ONE_SPECTRIER = 267, AB_PRESSURE = 46, AB_TRACE = 36, AB_IMPOSTER = 150,
    AB_INTREPID_SWORD = 234, AB_DAUNTLESS_SHIELD = 235, AB_DOWNLOAD = 88,
    AB_SCREEN_CLEANER = 251, AB_FORECAST = 59, AB_RKS_SYSTEM = 225, AB_GUARD_DOG = 275,
    AB_RATTLED = 155, AB_NEUTRALIZING_GAS = 256, AB_SCRAPPY = 113,
    AB_WONDER_GUARD = 25, AB_ILLUSION = 149, AB_POWER_CONSTRUCT = 211, AB_RECEIVER = 222,
    AB_MULTITYPE = 121, AB_STANCE_CHANGE = 176, AB_SCHOOLING = 208;

// Mold Breaker family (MOLD_BREAKER, TERAVOLT, TURBOBLAZE)
constexpr int32_t MOLD_BREAKER_IDS[3] = {104, 163, 164};

// Explosion/Self-Destruct family (EXPLOSION, SELF_DESTRUCT, MIND_BLOWN, MISTY_EXPLOSION).
// Shared by damage.cpp (BP handling), post_hit.cpp (self-faint), move_exec_guards.cpp
// (Damp gate + abort-path self-faint per USER spec 2026-07-15, Task R2).
constexpr int32_t EXPLOSION_MOVE_IDS[4] = {120, 153, 720, 802};

// --- Items ---
constexpr int32_t ITEM_NONE = 0, ITEM_HEAVY_DUTY_BOOTS = 1120, ITEM_WHITE_HERB = 214,
    ITEM_EJECT_PACK = 1119, ITEM_ADRENALINE_ORB = 846, ITEM_DAMP_ROCK = 285,
    ITEM_HEAT_ROCK = 284, ITEM_SMOOTH_ROCK = 283, ITEM_ICY_ROCK = 282,
    ITEM_LIGHT_CLAY = 269, ITEM_TERRAIN_EXTENDER = 879, ITEM_ROOM_SERVICE = 1122,
    ITEM_IRON_BALL = 278, ITEM_AIR_BALLOON = 541;

// Entry-effect items (Soul Dew, RKS Memories). Terrain-seed item ids are defined file-local
// in effects.cpp (apply_terrain_seeds) and reused there.
constexpr int32_t ITEM_SOUL_DEW = 225,
    ITEM_FIRE_MEMORY = 901, ITEM_WATER_MEMORY = 902, ITEM_GRASS_MEMORY = 903,
    ITEM_ELECTRIC_MEMORY = 904, ITEM_ICE_MEMORY = 905, ITEM_FIGHTING_MEMORY = 906,
    ITEM_POISON_MEMORY = 907, ITEM_GROUND_MEMORY = 908, ITEM_FLYING_MEMORY = 909,
    ITEM_PSYCHIC_MEMORY = 910, ITEM_BUG_MEMORY = 911, ITEM_ROCK_MEMORY = 912,
    ITEM_GHOST_MEMORY = 913, ITEM_DRAGON_MEMORY = 914, ITEM_DARK_MEMORY = 915,
    ITEM_STEEL_MEMORY = 916, ITEM_FAIRY_MEMORY = 917;

// --- Status ---
constexpr int32_t STATUS_NONE = 0, STATUS_BURN = 1, STATUS_FREEZE = 2, STATUS_PARALYSIS = 3,
    STATUS_POISON = 4, STATUS_TOXIC = 5, STATUS_SLEEP = 6;

// --- Types ---
constexpr int32_t TYPE_NORMAL = 0, TYPE_FIRE = 1, TYPE_WATER = 2, TYPE_ELECTRIC = 3,
    TYPE_GRASS = 4, TYPE_ICE = 5, TYPE_FIGHTING = 6, TYPE_POISON = 7, TYPE_FLYING = 9,
    TYPE_GROUND = 8, TYPE_PSYCHIC = 10,
    TYPE_BUG = 11, TYPE_ROCK = 12, TYPE_GHOST = 13, TYPE_DRAGON = 14, TYPE_DARK = 15,
    TYPE_STEEL = 16, TYPE_FAIRY = 17;

// --- SideCondition ---
constexpr int32_t SC_REFLECT = 1, SC_LIGHT_SCREEN = 2, SC_AURORA_VEIL = 3, SC_STEALTH_ROCK = 4,
    SC_SPIKES_1 = 5, SC_SPIKES_2 = 6, SC_SPIKES_3 = 7, SC_TOXIC_SPIKES_1 = 8,
    SC_TOXIC_SPIKES_2 = 9, SC_STICKY_WEB = 10, SC_TAILWIND = 11, SC_LUCKY_CHANT = 12,
    SC_SAFEGUARD = 13;

// --- Weather ---
constexpr int32_t WEATHER_NONE = 0, WEATHER_SUNNY = 1, WEATHER_RAINY = 2, WEATHER_SANDSTORM = 3,
    WEATHER_HAIL = 4, WEATHER_HEAVY_RAIN = 5, WEATHER_HARSH_SUN = 6, WEATHER_STRONG_WIND = 7;

// --- Terrain ---
constexpr int32_t TERRAIN_NONE = 0, TERRAIN_ELECTRIC = 1, TERRAIN_GRASSY = 2,
    TERRAIN_PSYCHIC = 3, TERRAIN_MISTY = 4;

// --- PseudoWeather ---
constexpr int32_t PW_TRICK_ROOM = 1, PW_GRAVITY = 2;

// --- Volatile (IntFlag bits) ---
constexpr int32_t VOLATILE_CONFUSED = 1, VOLATILE_MINIMIZE = 1024, VOLATILE_DEFENSE_CURL = 2048,
    VOLATILE_FLASH_FIRE = 1048576,
    VOLATILE_LEECH_SEEDED = 2, VOLATILE_TAUNT_ACTIVE = 16, VOLATILE_ENCORE_ACTIVE = 8,
    VOLATILE_ATTRACTED = 8388608, VOLATILE_SUBSTITUTE = 4096, VOLATILE_TORMENT = 32,
    VOLATILE_PERISH_SONG_ACTIVE = 16384, VOLATILE_DESTINY_BOND = 8192,
    VOLATILE_IDENTIFIED = 134217728;

// --- VolatileEffect ---
constexpr int32_t VE_ROOST = 11,
    VE_TAUNT = 2, VE_ENCORE = 1, VE_DISABLE = 5, VE_PERISH_SONG = 3, VE_TRAPPED = 22,
    VE_OCTOLOCK = 23, VE_DROWSY = 20, VE_NIGHTMARE = 26, VE_NO_RETREAT = 28,
    VE_TRAPPED_SOURCE_ID = 33,
    VE_LASER_FOCUS = 25, VE_MAGNET_RISE = 8, VE_TELEKINESIS = 29,
    VE_LEECH_SEED_SOURCE_SLOT = 30,
    VE_GROUNDED = 24, VE_BOUND = 4, VE_BOUND_SOURCE_SLOT = 31, VE_BOUND_SOURCE_ID = 32,
    VE_THROAT_CHOPPED = 21,
    // int field = Move id being charged when it differs from the slot move (called two-turn:
    // Metronome/Copycat -> Solar Beam). Payload, never ticks (Showdown twoturnmove.onLockMove).
    VE_CHARGING_MOVE = 34;

// --- Species (Minior meteor form, for Shields Down status immunity) ---
constexpr int32_t SPECIES_MINIOR_METEOR = 7740001;

// --- Species: entry-effect form/identity sets (Soul Dew, Castform, Silvally) ---
constexpr int32_t SP_LATIAS = 380, SP_LATIOS = 381;
constexpr int32_t SP_CASTFORM = 351, SP_CASTFORM_SUNNY = 1051, SP_CASTFORM_RAINY = 1052,
    SP_CASTFORM_SNOWY = 1053;

// --- Moves (named, used directly in dispatch) ---
constexpr int32_t MOVE_NONE = 0, MOVE_STEALTH_ROCK = 446, MOVE_SPIKES = 191, MOVE_TOXIC_SPIKES = 390,
    MOVE_STICKY_WEB = 564, MOVE_DEFOG = 432, MOVE_REFLECT = 115, MOVE_LIGHT_SCREEN = 113,
    MOVE_AURORA_VEIL = 694, MOVE_TAILWIND = 366, MOVE_LUCKY_CHANT = 381, MOVE_SAFEGUARD = 219,
    MOVE_GRAVITY = 356, MOVE_TRICK_ROOM = 433, MOVE_MINIMIZE = 107, MOVE_GROWTH = 74,
    MOVE_AUTOTOMIZE = 475, MOVE_DEFENSE_CURL = 111, MOVE_REST = 156, MOVE_ROOST = 355,
    MOVE_HEAL_PULSE = 505, MOVE_WISH = 273, MOVE_STRENGTH_SAP = 668, MOVE_SWALLOW = 256;

// Volatile-setting move ids (dispatched by _apply_volatile_move).
constexpr int32_t MOVE_LEECH_SEED = 73, MOVE_TAUNT = 269, MOVE_ENCORE = 227, MOVE_FLATTER = 260,
    MOVE_SWAGGER = 207, MOVE_ATTRACT = 213, MOVE_SUBSTITUTE = 164, MOVE_DISABLE = 50,
    MOVE_TORMENT = 259, MOVE_PERISH_SONG = 195, MOVE_DESTINY_BOND = 194, MOVE_FORESIGHT = 193,
    MOVE_ODOR_SLEUTH = 316, MOVE_OCTOLOCK = 753, MOVE_YAWN = 281, MOVE_NIGHTMARE = 171,
    MOVE_BLOCK = 335, MOVE_MEAN_LOOK = 212, MOVE_TEETER_DANCE = 298, MOVE_NO_RETREAT = 748,
    MOVE_LASER_FOCUS = 673, MOVE_MAGNET_RISE = 393, MOVE_TELEKINESIS = 477, MOVE_ACUPRESSURE = 367,
    MOVE_CONFUSE_RAY = 109, MOVE_SUPERSONIC = 48, MOVE_SWEET_KISS = 186;

// Self-status move ids (dispatched by _apply_self_status_move).
constexpr int32_t MOVE_HELPING_HAND = 270, MOVE_FOLLOW_ME = 266, MOVE_RAGE_POWDER = 476,
    MOVE_FOCUS_ENERGY = 116, MOVE_IMPRISON = 286, MOVE_BELLY_DRUM = 187, MOVE_STOCKPILE = 254,
    MOVE_STUFF_CHEEKS = 747;

// --- Volatile: Helping Hand bit ---
constexpr int32_t VOLATILE_HELPING_HAND = 33554432;

} // namespace eff

#endif // NUZLOCKE_EFFECTS_CONSTS_H
